export const medicalPrompts = {
  greetings: [
    "Good morning! How can I assist you with your health today?",
    "Good afternoon! What medical questions do you have for me?",
    "Good evening! How can I help you with your health concerns?"
  ],
  askName: "Before we begin, may I know your name?",
  askSymptoms: "Can you please describe your symptoms?",
  askTemperature: "What is your current temperature?",
  askDuration: "How long have you been experiencing these symptoms?",
  advice: {
    cough: "For a cough, stay hydrated, try warm fluids, and use honey if appropriate. If it persists, consult a doctor.",
    dry_cough: "For a dry cough, sip warm liquids, use throat lozenges, and avoid irritants like smoke.",
    wet_cough: "For a wet cough, stay hydrated and consider using a humidifier. If it persists, consult a doctor.",
    fever: "For fever, rest, drink fluids, and use a cool compress. If it exceeds 100.4°F (38°C) or lasts more than 3 days, seek medical advice.",
    sneezing: "Sneezing may be due to allergies or a cold. Avoid allergens and rest.",
    headache: "For headaches, rest in a quiet, dark room, stay hydrated, and consider over-the-counter pain relief if needed.",
    migraine: "For migraines, rest in a dark, quiet room, use cold compresses, and avoid triggers. Consult a doctor if frequent.",
    sore_throat: "For a sore throat, gargle with warm salt water, drink warm fluids, and use throat lozenges.",
    runny_nose: "For a runny nose, stay hydrated, use saline nasal drops, and rest.",
    stuffy_nose: "For a stuffy nose, try steam inhalation, saline sprays, and keep your head elevated while resting.",
    nasal_congestion: "For nasal congestion, try steam inhalation and saline sprays.",
    body_ache: "For body aches, rest, stay hydrated, and consider mild pain relievers if needed.",
    muscle_pain: "For muscle pain, rest, gentle stretching, and over-the-counter pain relief may help.",
    joint_pain: "For joint pain, rest, ice, and gentle movement can help. If persistent, consult a doctor.",
    back_pain: "For back pain, rest, gentle stretching, and heat/cold packs may help. See a doctor if severe.",
    stomach_pain: "For stomach pain, rest and avoid heavy meals. If severe or persistent, consult a doctor.",
    abdominal_pain: "For abdominal pain, rest and stay hydrated. Seek medical attention if severe.",
    diarrhea: "For diarrhea, drink oral rehydration solutions and avoid dairy or fatty foods. See a doctor if it persists.",
    constipation: "For constipation, increase fiber and fluid intake, and stay active.",
    vomiting: "For vomiting, sip clear fluids slowly and rest. If vomiting is severe or persistent, seek medical care.",
    nausea: "For nausea, try small sips of clear fluids and bland foods.",
    dysentery: "For dysentery, drink plenty of fluids to avoid dehydration and seek medical attention promptly.",
    fatigue: "For fatigue, ensure adequate rest, hydration, and balanced nutrition.",
    dizziness: "For dizziness, sit or lie down until it passes. Stay hydrated. If severe, seek medical help.",
    chest_pain: "Chest pain can be serious. If severe or with shortness of breath, seek emergency care immediately.",
    palpitations: "For palpitations, rest and avoid stimulants. If persistent, consult a doctor.",
    shortness_of_breath: "Shortness of breath can be serious. If severe, seek emergency care immediately.",
    rash: "For a rash, avoid irritants and keep the area clean. If spreading or severe, consult a doctor.",
    itching: "For itching, avoid scratching and use soothing lotions.",
    allergy: "For allergies, avoid triggers and consider antihistamines.",
    eye_pain: "For eye pain, rest your eyes and avoid screens. If severe, see a doctor.",
    ear_pain: "For ear pain, avoid inserting objects and keep the ear dry. Consult a doctor if it persists.",
    toothache: "For toothache, rinse with warm salt water and see a dentist.",
    bleeding: "For bleeding, apply pressure. If it doesn't stop, seek medical attention.",
    swelling: "For swelling, rest and elevate the area. If severe, consult a doctor.",
    burn: "For minor burns, cool the area with water. For severe burns, seek emergency care.",
    wound: "For wounds, clean gently and cover with a sterile bandage.",
    insomnia: "For insomnia, maintain a regular sleep schedule and avoid screens before bed.",
    anxiety: "For anxiety, try deep breathing and relaxation techniques. Seek support if needed.",
    depression: "For depression, talk to someone you trust and consider professional help.",
    covid: "If you suspect COVID-19, isolate yourself and get tested. Follow local health guidelines.",
    flu: "For flu, rest, stay hydrated, and manage symptoms. Seek medical care if severe.",
    cold: "For a cold, rest, stay hydrated, and use over-the-counter remedies as needed.",
    dehydration: "For dehydration, drink fluids regularly. Severe dehydration needs medical attention.",
    heatstroke: "For heatstroke, move to a cool place, hydrate, and seek emergency care.",
    sunburn: "For sunburn, cool the skin and use soothing lotions.",
    insect_bite: "For insect bites, clean the area and use anti-itch cream.",
    food_poisoning: "For food poisoning, rest and stay hydrated. Seek medical care if severe.",
    chickenpox: "Chickenpox usually causes itchy rash and fever. Rest, stay hydrated, and avoid scratching. Consult a doctor for severe symptoms.",
    measles: "Measles causes rash, fever, cough, and red eyes. Rest, fluids, and isolation are important. Seek medical care.",
    mumps: "Mumps causes swollen cheeks/jaw and fever. Rest, fluids, and pain relief help. See a doctor for complications.",
    rubella: "Rubella causes mild fever and rash. Rest and fluids are helpful. Pregnant women should seek immediate care.",
    dengue: "Dengue causes high fever, pain, and rash. Rest, fluids, and paracetamol (not aspirin). Seek urgent care for bleeding or severe pain.",
    malaria: "Malaria causes fever, chills, and sweating. Seek medical attention for diagnosis and treatment.",
    typhoid: "Typhoid causes prolonged fever, headache, and stomach pain. Medical treatment is necessary.",
    tuberculosis: "Tuberculosis causes cough, fever, and weight loss. Medical evaluation and treatment are essential.",
    hepatitis: "Hepatitis causes jaundice, fatigue, and nausea. Rest, fluids, and medical care are important.",
    appendicitis: "Appendicitis causes severe lower right abdominal pain. Seek emergency medical care.",
    pneumonia: "Pneumonia causes cough, fever, and difficulty breathing. Medical evaluation is needed.",
    meningitis: "Meningitis causes severe headache, fever, and neck stiffness. Seek emergency care immediately.",
    epilepsy: "Epilepsy causes seizures. Ensure safety during a seizure and consult a neurologist.",
    sickle_cell: "Sickle cell anemia causes pain and anemia. Hydration and regular medical care are important.",
    thalassemia: "Thalassemia causes anemia. Regular blood tests and medical care are needed.",
    lupus: "Lupus can cause joint pain, rash, and fatigue. Regular follow-up with a doctor is important.",
    crohns: "Crohn's disease causes abdominal pain and diarrhea. Medical management is necessary.",
    celiac: "Celiac disease causes digestive issues after gluten. Avoid gluten and consult a doctor.",
    fibromyalgia: "Fibromyalgia causes widespread pain and fatigue. Regular exercise and stress management help.",
    psoriasis: "Psoriasis causes scaly skin patches. Moisturizers and prescribed creams help.",
    raynaud: "Raynaud's causes cold, numb fingers. Keep warm and avoid stress.",
    marfan: "Marfan syndrome affects connective tissue. Regular heart and eye checkups are important.",
    als: "ALS causes muscle weakness. Supportive care and neurologist follow-up are needed.",
    ebola: "Ebola causes fever, bleeding, and weakness. Seek emergency care and isolation.",
    zika: "Zika causes fever, rash, and joint pain. Rest, fluids, and mosquito protection are important.",
    lyme: "Lyme disease causes rash and joint pain. Early antibiotics are important.",
    sars: "SARS causes fever and respiratory symptoms. Isolation and medical care are needed.",
    mers: "MERS causes fever and cough. Seek medical care and isolation.",
    rabies: "Rabies is fatal after symptoms start. Immediate post-exposure vaccination is critical.",
    anthrax: "Anthrax causes skin sores or breathing problems. Seek urgent medical care.",
    plague: "Plague causes fever and swollen lymph nodes. Seek urgent medical care.",
    cardiovascular_disease: "Cardiovascular diseases include heart attack, angina, and coronary artery disease. If you have chest pain, shortness of breath, or severe discomfort, seek emergency care immediately. For ongoing management, follow your doctor's advice, take prescribed medications, maintain a healthy diet, exercise regularly, and avoid smoking.",
    cancer: "Cancer is a complex group of diseases. If you suspect cancer or have symptoms like unexplained weight loss, lumps, or persistent pain, consult a specialist promptly. Early diagnosis and treatment are crucial.",
    chronic_respiratory_disorder: "Chronic respiratory disorders like COPD and asthma require regular medication, avoiding triggers (like smoke and dust), and following your doctor's plan. If you have difficulty breathing, seek medical help.",
    lower_respiratory_problem: "Lower respiratory problems such as pneumonia or bronchiolitis can cause cough, fever, and difficulty breathing. Rest, stay hydrated, and seek medical attention, especially if symptoms are severe.",
    skin_condition: "Skin conditions like eczema, psoriasis, and dermatitis require proper skincare, avoiding irritants, and following your doctor's advice. If you have severe rashes or itching, consult a dermatologist.",
    gastrointestinal_disorder: "Gastrointestinal disorders like IBS and GERD require dietary changes, medications, and stress management. If you have severe abdominal pain or persistent symptoms, seek medical attention.",
    neurological_disorder: "Neurological disorders like epilepsy and migraines require regular follow-up with a neurologist. If you experience seizures or severe headaches, seek immediate medical help.",
    autoimmune_disorder: "Autoimmune disorders like lupus and rheumatoid arthritis require regular monitoring and treatment. If you have joint pain or fatigue, consult your doctor for management options."
  },
  farewell: "Thank you for chatting with me! Take care of your health."
};